# Generated by Django 6.0.8 on 2026-08-21 08:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import iam.models
import regulatory.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iam", "0026_delete_cacheversion"),
        ("tprm", "0019_null_perimeter_on_enclave_audits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulatoryDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "record_id",
                    models.CharField(
                        max_length=160,
                        validators=[
                            regulatory.validators.validate_regulatory_identifier
                        ],
                    ),
                ),
                ("title_zh", models.CharField(max_length=1000)),
                ("title_en", models.CharField(blank=True, max_length=1000)),
                ("issuer", models.CharField(max_length=500)),
                (
                    "authority_level",
                    models.CharField(
                        choices=[
                            ("law", "Law"),
                            ("administrative_regulation", "Administrative regulation"),
                            ("departmental_rule", "Departmental rule"),
                            (
                                "regulatory_normative_document",
                                "Regulatory normative document",
                            ),
                            ("mandatory_standard", "Mandatory standard"),
                            ("recommended_standard", "Recommended standard"),
                            ("internal_policy", "Internal policy"),
                            ("interpretive_material", "Interpretive material"),
                            ("enforcement_material", "Enforcement material"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "territories",
                    models.JSONField(
                        default=list,
                        validators=[
                            regulatory.validators.validate_non_empty_string_list
                        ],
                    ),
                ),
                (
                    "regulated_entity_scopes",
                    models.JSONField(
                        default=list,
                        validators=[
                            regulatory.validators.validate_non_empty_string_list
                        ],
                    ),
                ),
                (
                    "domains",
                    models.JSONField(
                        default=list,
                        validators=[regulatory.validators.validate_regulatory_domains],
                    ),
                ),
                (
                    "coverage_priority",
                    models.CharField(
                        blank=True,
                        choices=[("P0", "P0"), ("P1", "P1"), ("P2", "P2")],
                        max_length=2,
                    ),
                ),
                (
                    "coverage_stage",
                    models.CharField(
                        choices=[
                            ("source_metadata", "Source metadata"),
                            ("provision_indexed", "Provision indexed"),
                            ("obligations_proposed", "Obligations proposed"),
                            ("obligations_reviewed", "Obligations reviewed"),
                        ],
                        default="obligations_proposed",
                        max_length=32,
                    ),
                ),
                (
                    "applicability_fact_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[regulatory.validators.validate_string_list],
                    ),
                ),
                ("selection_rationale", models.TextField(blank=True, max_length=2000)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
            ],
            options={
                "ordering": ["record_id"],
                "permissions": [
                    (
                        "ingest_regulatoryrecord",
                        "Can atomically ingest a regulatory record chain",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityDocumentRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "registration_kind",
                    models.CharField(
                        choices=[("synthetic_pilot", "Synthetic pilot")],
                        default="synthetic_pilot",
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200)),
                (
                    "payload_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regulatory_document_registrations",
                        to="tprm.entity",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "ingested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regulatory_chain_ingestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entity_registrations",
                        to="regulatory.regulatorydocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegulatoryDocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "record_id",
                    models.CharField(
                        max_length=160,
                        validators=[
                            regulatory.validators.validate_regulatory_identifier
                        ],
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "recorded_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("recorded_to", models.DateTimeField(blank=True, null=True)),
                (
                    "provenance_method",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("parser", "Parser"),
                            ("model_proposal", "Model proposal"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provenance_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("provenance_created_by", models.CharField(max_length=300)),
                (
                    "parser_version",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("model_name", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "prompt_version",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "retrieval_version",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("version_label", models.CharField(max_length=300)),
                (
                    "document_no",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            (
                                "published_future_effective",
                                "Published, future effective",
                            ),
                            ("effective", "Effective"),
                            (
                                "active_no_explicit_commencement",
                                "Active without explicit commencement",
                            ),
                            ("superseded", "Superseded"),
                            ("repealed", "Repealed"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=48,
                    ),
                ),
                ("status_as_of", models.DateField()),
                (
                    "effective_basis",
                    models.CharField(
                        choices=[
                            ("explicit_date", "Explicit date"),
                            ("publication_clause", "Publication clause"),
                            (
                                "no_explicit_commencement_clause",
                                "No explicit commencement clause",
                            ),
                            ("unresolved", "Unresolved"),
                        ],
                        max_length=48,
                    ),
                ),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("transition_end", models.DateField(blank=True, null=True)),
                ("repeal_date", models.DateField(blank=True, null=True)),
                ("source_url", models.URLField(max_length=2048)),
                (
                    "source_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                (
                    "content_storage_policy",
                    models.CharField(
                        choices=[
                            ("metadata_only", "Metadata only"),
                            ("official_snapshot", "Official snapshot"),
                            ("licensed_copy", "Licensed copy"),
                        ],
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=4000)),
                ("source_checked_on", models.DateField()),
                (
                    "metadata_confidence",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("partial", "Partial"),
                            ("unresolved", "Unresolved"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "legal_review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="unreviewed",
                        max_length=16,
                    ),
                ),
                ("legal_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "legal_reviewed_by",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="regulatory.regulatorydocument",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "previous_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="regulatory.regulatorydocumentversion",
                    ),
                ),
            ],
            options={
                "ordering": ["record_id", "revision"],
            },
        ),
        migrations.CreateModel(
            name="RegulatoryObligation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "record_id",
                    models.CharField(
                        max_length=160,
                        validators=[
                            regulatory.validators.validate_regulatory_identifier
                        ],
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "recorded_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("recorded_to", models.DateTimeField(blank=True, null=True)),
                (
                    "provenance_method",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("parser", "Parser"),
                            ("model_proposal", "Model proposal"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provenance_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("provenance_created_by", models.CharField(max_length=300)),
                (
                    "parser_version",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("model_name", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "prompt_version",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "retrieval_version",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("title_zh", models.CharField(max_length=1000)),
                (
                    "authority_level",
                    models.CharField(
                        choices=[
                            ("law", "Law"),
                            ("administrative_regulation", "Administrative regulation"),
                            ("departmental_rule", "Departmental rule"),
                            (
                                "regulatory_normative_document",
                                "Regulatory normative document",
                            ),
                            ("mandatory_standard", "Mandatory standard"),
                            ("recommended_standard", "Recommended standard"),
                            ("internal_policy", "Internal policy"),
                            ("interpretive_material", "Interpretive material"),
                            ("enforcement_material", "Enforcement material"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("must", "Must"),
                            ("must_not", "Must not"),
                            ("should", "Should"),
                            ("may", "May"),
                            ("organisation_defined", "Organisation defined"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subject", models.CharField(max_length=1000)),
                ("action", models.TextField(max_length=4000)),
                ("object", models.TextField(blank=True, max_length=2000, null=True)),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[regulatory.validators.validate_string_list],
                    ),
                ),
                (
                    "exceptions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[regulatory.validators.validate_string_list],
                    ),
                ),
                (
                    "deadline_kind",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("fixed_date", "Fixed date"),
                            ("duration_after_trigger", "Duration after trigger"),
                            ("periodic", "Periodic"),
                            ("without_undue_delay", "Without undue delay"),
                            ("needs_review", "Needs review"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "deadline_value",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "deadline_rule_id",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "expected_evidence",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[regulatory.validators.validate_string_list],
                    ),
                ),
                (
                    "penalty_or_consequence",
                    models.TextField(blank=True, max_length=4000, null=True),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("machine_proposed", "Machine proposed"),
                            ("analyst_reviewed", "Analyst reviewed"),
                            ("legal_reviewed", "Legal reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="machine_proposed",
                        max_length=24,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "uncertainties",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[regulatory.validators.validate_string_list],
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "previous_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="regulatory.regulatoryobligation",
                    ),
                ),
            ],
            options={
                "ordering": ["record_id", "revision"],
                "permissions": [
                    (
                        "transition_regulatoryobligation",
                        "Can transition a regulatory obligation review",
                    ),
                    (
                        "legal_review_regulatoryobligation",
                        "Can perform the separate legal review of a regulatory obligation",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegulatoryObligationReviewEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("machine_proposed", "Machine proposed"),
                            ("analyst_reviewed", "Analyst reviewed"),
                            ("legal_reviewed", "Legal reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("machine_proposed", "Machine proposed"),
                            ("analyst_reviewed", "Analyst reviewed"),
                            ("legal_reviewed", "Legal reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("rationale", models.TextField(max_length=4000)),
                ("idempotency_key", models.CharField(max_length=200)),
                (
                    "payload_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regulatory_obligation_review_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_events",
                        to="regulatory.regulatoryobligation",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="RegulatoryProvision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "record_id",
                    models.CharField(
                        max_length=160,
                        validators=[
                            regulatory.validators.validate_regulatory_identifier
                        ],
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "recorded_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("recorded_to", models.DateTimeField(blank=True, null=True)),
                (
                    "provenance_method",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("parser", "Parser"),
                            ("model_proposal", "Model proposal"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provenance_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("provenance_created_by", models.CharField(max_length=300)),
                (
                    "parser_version",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("model_name", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "prompt_version",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "retrieval_version",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("article", models.CharField(max_length=300)),
                ("heading", models.CharField(blank=True, max_length=1000, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "source_locator_kind",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("page", "Page"),
                            ("page_bbox", "Page bounding box"),
                            ("dom_selector", "DOM selector"),
                            ("annex", "Annex"),
                            ("table_cell", "Table cell"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_locator_value", models.CharField(max_length=1000)),
                (
                    "content_hash",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provisions",
                        to="regulatory.regulatorydocumentversion",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "previous_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="regulatory.regulatoryprovision",
                    ),
                ),
            ],
            options={
                "ordering": ["record_id", "revision"],
            },
        ),
        migrations.CreateModel(
            name="RegulatoryObligationProvision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provision_links",
                        to="regulatory.regulatoryobligation",
                    ),
                ),
                (
                    "provision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligation_links",
                        to="regulatory.regulatoryprovision",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="regulatoryobligation",
            name="provisions",
            field=models.ManyToManyField(
                related_name="obligations",
                through="regulatory.RegulatoryObligationProvision",
                to="regulatory.regulatoryprovision",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocument",
            constraint=models.UniqueConstraint(
                fields=("folder", "record_id"), name="reg_doc_folder_record_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_published", False)),
                name="reg_doc_not_published",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("coverage_stage", "obligations_proposed")),
                name="reg_doc_phase1_proposed",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitydocumentregistration",
            constraint=models.UniqueConstraint(
                fields=("entity", "document"), name="reg_entity_document_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="entitydocumentregistration",
            constraint=models.UniqueConstraint(
                fields=("folder", "idempotency_key"), name="reg_ingest_idempotency_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="entitydocumentregistration",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_published", False)),
                name="reg_entity_doc_not_published",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.UniqueConstraint(
                fields=("folder", "record_id", "revision"),
                name="reg_ver_folder_record_rev_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recorded_to__isnull", True)),
                fields=("folder", "record_id"),
                name="reg_ver_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="reg_ver_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recorded_to__isnull", True),
                    ("recorded_to__gt", models.F("recorded_from")),
                    _connector="OR",
                ),
                name="reg_ver_recorded_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="reg_ver_valid_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["effective", "published_future_effective"]),
                        _negated=True,
                    ),
                    ("valid_from__isnull", False),
                    _connector="OR",
                ),
                name="reg_ver_active_valid_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_date__isnull", True),
                    ("valid_from", models.F("effective_date")),
                    _connector="OR",
                ),
                name="reg_ver_effective_valid_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status_as_of__lte", models.F("source_checked_on"))
                ),
                name="reg_ver_status_source_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("transition_end__isnull", True),
                    models.Q(
                        ("effective_date__isnull", False),
                        ("transition_end__gte", models.F("effective_date")),
                    ),
                    _connector="OR",
                ),
                name="reg_ver_transition_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "repealed"), _negated=True),
                    models.Q(
                        ("repeal_date__isnull", False),
                        ("valid_to", models.F("repeal_date")),
                    ),
                    _connector="OR",
                ),
                name="reg_ver_repeal_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "superseded"), _negated=True),
                    ("valid_to__isnull", False),
                    _connector="OR",
                ),
                name="reg_ver_superseded_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "status__in",
                            [
                                "effective",
                                "active_no_explicit_commencement",
                                "published_future_effective",
                            ],
                        ),
                        _negated=True,
                    ),
                    ("repeal_date__isnull", True),
                    _connector="OR",
                ),
                name="reg_ver_active_not_repealed",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("content_storage_policy", "metadata_only"),
                    models.Q(
                        ("source_hash__isnull", False),
                        models.Q(("source_hash", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="reg_ver_stored_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_storage_policy", "metadata_only")),
                name="reg_ver_phase1_metadata_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("legal_review_status", "unreviewed"),
                        ("legal_reviewed_at__isnull", True),
                        ("legal_reviewed_by__isnull", True),
                    ),
                    models.Q(
                        ("legal_review_status", "reviewed"),
                        ("legal_reviewed_at__isnull", False),
                        ("legal_reviewed_by__isnull", False),
                        models.Q(("legal_reviewed_by", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="reg_ver_legal_review_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("legal_review_status", "unreviewed"),
                    ("legal_reviewed_at__isnull", True),
                    ("legal_reviewed_by__isnull", True),
                ),
                name="reg_ver_phase1_unreviewed",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorydocumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_published", False)),
                name="reg_ver_not_published",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligationreviewevent",
            constraint=models.UniqueConstraint(
                fields=("obligation", "sequence"), name="reg_obl_review_sequence_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligationreviewevent",
            constraint=models.UniqueConstraint(
                fields=("folder", "idempotency_key"), name="reg_review_idempotency_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligationreviewevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)),
                name="reg_obl_review_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligationreviewevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("from_status", "machine_proposed"),
                        ("sequence", 1),
                        ("to_status", "analyst_reviewed"),
                    ),
                    models.Q(
                        ("from_status", "analyst_reviewed"),
                        ("sequence", 2),
                        ("to_status", "legal_reviewed"),
                    ),
                    _connector="OR",
                ),
                name="reg_obl_review_phase1_edge",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligationreviewevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_published", False)),
                name="reg_obl_review_not_published",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryprovision",
            constraint=models.UniqueConstraint(
                fields=("folder", "record_id", "revision"),
                name="reg_prov_folder_record_rev_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryprovision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recorded_to__isnull", True)),
                fields=("folder", "record_id"),
                name="reg_prov_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryprovision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="reg_prov_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryprovision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recorded_to__isnull", True),
                    ("recorded_to__gt", models.F("recorded_from")),
                    _connector="OR",
                ),
                name="reg_prov_recorded_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryprovision",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_published", False)),
                name="reg_prov_not_published",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryprovision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("text__isnull", True), ("text", ""), _connector="OR"
                ),
                name="reg_prov_phase1_no_text",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligationprovision",
            constraint=models.UniqueConstraint(
                fields=("obligation", "provision"), name="reg_obl_provision_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligationprovision",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_published", False)),
                name="reg_obl_prov_not_published",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligation",
            constraint=models.UniqueConstraint(
                fields=("folder", "record_id", "revision"),
                name="reg_obl_folder_record_rev_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recorded_to__isnull", True)),
                fields=("folder", "record_id"),
                name="reg_obl_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="reg_obl_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recorded_to__isnull", True),
                    ("recorded_to__gt", models.F("recorded_from")),
                    _connector="OR",
                ),
                name="reg_obl_recorded_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="reg_obl_valid_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="reg_obl_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_status", "machine_proposed")),
                name="reg_obl_phase1_initial",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_published", False)),
                name="reg_obl_not_published",
            ),
        ),
    ]
