# Generated by Django 6.0.8 on 2026-08-24 02:06

import django.db.models.deletion
import iam.models
import regulatory.validators
import uuid
from django.conf import settings
from django.db import migrations, models


def refuse_reverse_with_correction_history(apps, schema_editor):
    correction_event = apps.get_model(
        "regulatory",
        "RegulatoryChainCorrectionEvent",
    )
    if correction_event.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError(
            "Cannot remove regulatory correction audit history; retain migration 0002."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0026_delete_cacheversion"),
        ("regulatory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulatoryChainCorrectionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "correction_kind",
                    models.CharField(
                        choices=[("recorded_time", "Recorded-time correction")],
                        default="recorded_time",
                        max_length=24,
                    ),
                ),
                (
                    "digest_schema",
                    models.CharField(
                        default="regulatory-chain-correction/v1",
                        editable=False,
                        max_length=64,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("rationale", models.TextField(max_length=4000)),
                ("idempotency_key", models.CharField(max_length=200)),
                (
                    "payload_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                (
                    "before_payload_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                (
                    "after_payload_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="regulatorydocument",
            options={
                "ordering": ["record_id"],
                "permissions": [
                    (
                        "ingest_regulatoryrecord",
                        "Can atomically ingest a regulatory record chain",
                    ),
                    (
                        "correct_regulatoryrecord",
                        "Can atomically correct a current regulatory record chain",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="regulatorydocumentversion",
            index=models.Index(
                fields=["folder", "document", "recorded_from"],
                name="reg_ver_doc_asof_idx",
            ),
        ),
        migrations.AddField(
            model_name="regulatorychaincorrectionevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="regulatory_chain_corrections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="regulatorychaincorrectionevent",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_events",
                to="regulatory.regulatorydocument",
            ),
        ),
        migrations.AddField(
            model_name="regulatorychaincorrectionevent",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
        migrations.AddField(
            model_name="regulatorychaincorrectionevent",
            name="previous_document_version",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_events_as_previous",
                to="regulatory.regulatorydocumentversion",
            ),
        ),
        migrations.AddField(
            model_name="regulatorychaincorrectionevent",
            name="previous_obligation",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_events_as_previous",
                to="regulatory.regulatoryobligation",
            ),
        ),
        migrations.AddField(
            model_name="regulatorychaincorrectionevent",
            name="previous_provision",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_events_as_previous",
                to="regulatory.regulatoryprovision",
            ),
        ),
        migrations.AddField(
            model_name="regulatorychaincorrectionevent",
            name="successor_document_version",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_events_as_successor",
                to="regulatory.regulatorydocumentversion",
            ),
        ),
        migrations.AddField(
            model_name="regulatorychaincorrectionevent",
            name="successor_obligation",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_events_as_successor",
                to="regulatory.regulatoryobligation",
            ),
        ),
        migrations.AddField(
            model_name="regulatorychaincorrectionevent",
            name="successor_provision",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_events_as_successor",
                to="regulatory.regulatoryprovision",
            ),
        ),
        migrations.AddIndex(
            model_name="regulatorychaincorrectionevent",
            index=models.Index(
                fields=["folder", "document", "occurred_at"],
                name="reg_correction_doc_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.UniqueConstraint(
                fields=("folder", "idempotency_key"),
                name="reg_correction_idempotency_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.UniqueConstraint(
                fields=("previous_document_version",),
                name="reg_correction_previous_ver_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.UniqueConstraint(
                fields=("successor_document_version",),
                name="reg_correction_successor_ver_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.UniqueConstraint(
                fields=("previous_provision",), name="reg_correction_previous_prov_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.UniqueConstraint(
                fields=("successor_provision",),
                name="reg_correction_successor_prov_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.UniqueConstraint(
                fields=("previous_obligation",), name="reg_correction_previous_obl_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.UniqueConstraint(
                fields=("successor_obligation",),
                name="reg_correction_successor_obl_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("correction_kind", "recorded_time")),
                name="reg_correction_recorded_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("digest_schema", "regulatory-chain-correction/v1")),
                name="reg_correction_digest_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("before_payload_sha256", models.F("after_payload_sha256")),
                    _negated=True,
                ),
                name="reg_correction_payload_changed",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "previous_document_version",
                        models.F("successor_document_version"),
                    ),
                    _negated=True,
                ),
                name="reg_correction_version_changed",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("previous_provision", models.F("successor_provision")),
                    _negated=True,
                ),
                name="reg_correction_provision_changed",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("previous_obligation", models.F("successor_obligation")),
                    _negated=True,
                ),
                name="reg_correction_obligation_changed",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("rationale", ""), _negated=True),
                name="reg_correction_rationale_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatorychaincorrectionevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_published", False)),
                name="reg_correction_not_published",
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=refuse_reverse_with_correction_history,
        ),
    ]
