# Generated by Django 6.0.8 on 2026-08-24 03:41

import django.db.models.deletion
import django.utils.timezone
import iam.models
import regulatory.validators
import uuid
from django.conf import settings
from django.db import migrations, models


def refuse_reverse_with_applicability_history(apps, schema_editor):
    applicability_decision = apps.get_model(
        "regulatory",
        "RegulatoryApplicabilityDecision",
    )
    if applicability_decision.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError(
            "Cannot remove regulatory applicability history; retain migration 0003."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0026_delete_cacheversion"),
        ("regulatory", "0002_regulatorychaincorrectionevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulatoryApplicabilityDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "record_id",
                    models.CharField(
                        max_length=160,
                        validators=[
                            regulatory.validators.validate_regulatory_identifier
                        ],
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "recorded_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("recorded_to", models.DateTimeField(blank=True, null=True)),
                (
                    "provenance_method",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("parser", "Parser"),
                            ("model_proposal", "Model proposal"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provenance_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("provenance_created_by", models.CharField(max_length=300)),
                (
                    "parser_version",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "prompt_version",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "retrieval_version",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("legal_entity", "Legal entity")],
                        default="legal_entity",
                        editable=False,
                        max_length=24,
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(
                        default=("SYNTHETIC-ENTITY-INSTITUTION-TYPE-BANK-001"),
                        max_length=160,
                        validators=[
                            regulatory.validators.validate_regulatory_identifier
                        ],
                    ),
                ),
                ("rule_version", models.PositiveIntegerField(default=1)),
                ("rule_snapshot", models.JSONField()),
                (
                    "fact_snapshot_id",
                    models.CharField(
                        max_length=160,
                        validators=[
                            regulatory.validators.validate_regulatory_identifier
                        ],
                    ),
                ),
                ("fact_snapshot", models.JSONField()),
                (
                    "missing_fact_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[regulatory.validators.validate_string_list],
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("applicable", "Applicable"),
                            ("not_applicable", "Not applicable"),
                            ("needs_review", "Needs review"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "rationale_code",
                    models.CharField(
                        choices=[
                            ("rule_satisfied", "Rule satisfied"),
                            ("rule_not_satisfied", "Rule not satisfied"),
                            (
                                "missing_or_unknown_fact",
                                "Missing or unknown fact",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("rationale", models.TextField(max_length=4000)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[("draft", "Draft")],
                        default="draft",
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("is_binding", models.BooleanField(default=False, editable=False)),
                (
                    "digest_schema",
                    models.CharField(
                        default="regulatory-applicability-evaluation/v1",
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "evaluator_profile",
                    models.CharField(
                        default="synthetic-single-condition/v1",
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "rule_snapshot_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                (
                    "fact_snapshot_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                (
                    "semantic_payload_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                (
                    "request_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicability_decisions",
                        to="regulatory.regulatoryobligation",
                    ),
                ),
                (
                    "previous_revision",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="regulatory.regulatoryapplicabilitydecision",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regulatory_applicability_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicability_decisions",
                        to="regulatory.entitydocumentregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["record_id", "revision"],
                "permissions": [
                    (
                        "record_regulatoryapplicability",
                        "Can record a deterministic regulatory applicability evaluation",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="regulatoryapplicabilitydecision",
            index=models.Index(
                fields=[
                    "folder",
                    "registration",
                    "obligation",
                    "recorded_from",
                ],
                name="reg_app_dec_asof_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.UniqueConstraint(
                fields=("folder", "record_id", "revision"),
                name="reg_app_dec_record_rev_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.UniqueConstraint(
                fields=("folder", "fact_snapshot_id", "revision"),
                name="reg_app_fact_record_rev_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recorded_to__isnull", True)),
                fields=("folder", "registration", "obligation", "rule_id"),
                name="reg_app_dec_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.UniqueConstraint(
                fields=("previous_revision",),
                name="reg_app_dec_previous_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.UniqueConstraint(
                fields=("folder", "idempotency_key"),
                name="reg_app_dec_idem_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="reg_app_dec_revision_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recorded_to__isnull", True),
                    ("recorded_to__gt", models.F("recorded_from")),
                    _connector="OR",
                ),
                name="reg_app_dec_recorded_int",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="reg_app_dec_valid_int",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_type", "legal_entity")),
                name="reg_app_dec_scope_legal",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "rule_id",
                        "SYNTHETIC-ENTITY-INSTITUTION-TYPE-BANK-001",
                    )
                ),
                name="reg_app_dec_rule_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("rule_version", 1)),
                name="reg_app_dec_rule_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_status", "draft")),
                name="reg_app_dec_draft",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_binding", False)),
                name="reg_app_dec_nonbinding",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("digest_schema", "regulatory-applicability-evaluation/v1")
                ),
                name="reg_app_dec_digest_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("evaluator_profile", "synthetic-single-condition/v1")
                ),
                name="reg_app_dec_eval_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("rationale", ""), _negated=True),
                name="reg_app_dec_rationale",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("rationale_code", "rule_satisfied"),
                        ("result", "applicable"),
                    ),
                    models.Q(
                        ("rationale_code", "rule_not_satisfied"),
                        ("result", "not_applicable"),
                    ),
                    models.Q(
                        ("rationale_code", "missing_or_unknown_fact"),
                        ("result", "needs_review"),
                    ),
                    _connector="OR",
                ),
                name="reg_app_dec_result_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoryapplicabilitydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_published", False)),
                name="reg_app_dec_not_published",
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=refuse_reverse_with_applicability_history,
        ),
    ]
