# Generated by Django 6.0.8 on 2026-08-24 09:07

import django.db.models.deletion
import iam.models
import regulatory.validators
import uuid
from django.conf import settings
from django.db import migrations, models


def refuse_reverse_with_applicability_review_history(apps, schema_editor):
    review_disposition = apps.get_model(
        "regulatory",
        "RegulatoryApplicabilityReviewDisposition",
    )
    if review_disposition.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError(
            "Cannot remove regulatory applicability review history; retain "
            "migration 0004."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0026_delete_cacheversion"),
        ("regulatory", "0003_regulatoryapplicabilitydecision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulatoryApplicabilityReviewDisposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "decision_semantic_payload_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "from_disposition",
                    models.CharField(
                        choices=[
                            ("not_reviewed", "Not reviewed"),
                            (
                                "no_correction_requested",
                                "No correction requested",
                            ),
                            ("correction_requested", "Correction requested"),
                            ("unable_to_complete", "Unable to complete"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "to_disposition",
                    models.CharField(
                        choices=[
                            ("not_reviewed", "Not reviewed"),
                            (
                                "no_correction_requested",
                                "No correction requested",
                            ),
                            ("correction_requested", "Correction requested"),
                            ("unable_to_complete", "Unable to complete"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("review_completed", "Review completed"),
                            (
                                "fact_correction_required",
                                "Fact correction required",
                            ),
                            (
                                "evidence_correction_required",
                                "Evidence correction required",
                            ),
                            (
                                "provenance_correction_required",
                                "Provenance correction required",
                            ),
                            (
                                "scope_or_parent_correction_required",
                                "Scope or parent correction required",
                            ),
                            (
                                "other_correction_required",
                                "Other correction required",
                            ),
                            ("insufficient_evidence", "Insufficient evidence"),
                            (
                                "conflicting_information",
                                "Conflicting information",
                            ),
                            (
                                "insufficient_authority_or_scope",
                                "Insufficient authority or scope",
                            ),
                            ("other_unresolved", "Other unresolved"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.TextField(max_length=4000)),
                ("occurred_at", models.DateTimeField(editable=False)),
                (
                    "digest_profile",
                    models.CharField(
                        default=("regulatory-applicability-review-disposition/v1"),
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "event_payload_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                (
                    "request_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[regulatory.validators.validate_sha256],
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200)),
                (
                    "is_binding",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_dispositions",
                        to="regulatory.regulatoryapplicabilitydecision",
                    ),
                ),
                (
                    "decision_recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name=(
                            "regulatory_applicability_reviews_as_decision_recorder"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "previous_disposition",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor_dispositions",
                        to=("regulatory.regulatoryapplicabilityreviewdisposition"),
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name=("regulatory_applicability_reviews_as_reviewer"),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["decision_id", "sequence"],
                "permissions": [
                    (
                        "review_regulatoryapplicability",
                        "Can review an exact regulatory applicability evaluation",
                    )
                ],
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["folder", "decision", "occurred_at"],
                        name="reg_app_rev_dec_time_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("decision", "sequence"),
                        name="reg_app_rev_dec_seq_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(previous_disposition__isnull=True),
                        fields=("decision",),
                        name="reg_app_rev_one_root",
                    ),
                    models.UniqueConstraint(
                        fields=("previous_disposition",),
                        name="reg_app_rev_prev_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("folder", "idempotency_key"),
                        name="reg_app_rev_idem_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(sequence__gte=1),
                        name="reg_app_rev_seq_pos",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                sequence=1,
                                previous_disposition__isnull=True,
                                from_disposition="not_reviewed",
                            )
                            | (
                                models.Q(
                                    sequence__gte=2,
                                    previous_disposition__isnull=False,
                                )
                                & models.Q(
                                    from_disposition__in=(
                                        "no_correction_requested",
                                        "correction_requested",
                                        "unable_to_complete",
                                    )
                                )
                            )
                        ),
                        name="reg_app_rev_root_succ",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                to_disposition="no_correction_requested",
                                reason_code="review_completed",
                            )
                            | models.Q(
                                to_disposition="correction_requested",
                                reason_code__in=(
                                    "fact_correction_required",
                                    "evidence_correction_required",
                                    "provenance_correction_required",
                                    "scope_or_parent_correction_required",
                                    "other_correction_required",
                                ),
                            )
                            | models.Q(
                                to_disposition="unable_to_complete",
                                reason_code__in=(
                                    "insufficient_evidence",
                                    "conflicting_information",
                                    "insufficient_authority_or_scope",
                                    "other_unresolved",
                                ),
                            )
                        ),
                        name="reg_app_rev_reason_target",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(rationale=""),
                        name="reg_app_rev_rationale",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(idempotency_key=""),
                        name="reg_app_rev_idem_present",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            digest_profile=(
                                "regulatory-applicability-review-disposition/v1"
                            )
                        ),
                        name="reg_app_rev_digest_profile",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(is_binding=False),
                        name="reg_app_rev_nonbinding",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(is_published=False),
                        name="reg_app_rev_not_published",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(reviewer=models.F("decision_recorded_by")),
                        name="reg_app_rev_actor_separate",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(previous_disposition=models.F("id")),
                        name="reg_app_rev_prev_not_self",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=refuse_reverse_with_applicability_review_history,
        ),
    ]
